In [1]:

#TASK 01
import numpy as np

arr1 = np.full((10, 10), 4)
values = np.arange(1, 101)
arr2 = values.reshape((10, 10))
result = arr1 * arr2
print(result)



[[  4   8  12  16  20  24  28  32  36  40]
 [ 44  48  52  56  60  64  68  72  76  80]
 [ 84  88  92  96 100 104 108 112 116 120]
 [124 128 132 136 140 144 148 152 156 160]
 [164 168 172 176 180 184 188 192 196 200]
 [204 208 212 216 220 224 228 232 236 240]
 [244 248 252 256 260 264 268 272 276 280]
 [284 288 292 296 300 304 308 312 316 320]
 [324 328 332 336 340 344 348 352 356 360]
 [364 368 372 376 380 384 388 392 396 400]]


In [2]:
#TASK 02
import numpy as np

lst1 = list(range(10,-1,-2))
lst2 = list(range(0,11))
combine = lst1 + lst2
print(combine)
arr = np.array(combine)
print(arr)



[10, 8, 6, 4, 2, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10  8  6  4  2  0  0  1  2  3  4  5  6  7  8  9 10]


In [3]:
#TASK 03
import numpy as np

#flatten method
print(arr)
arr2 = arr.flatten()
arr2[1] = 10
print("Original array: ", arr)
print("Flattened array:", arr2)

#ravel method
arr3 = arr.ravel()
print("Original array: ",arr)
print("Ravel array: ", arr3)




[10  8  6  4  2  0  0  1  2  3  4  5  6  7  8  9 10]
Original array:  [10  8  6  4  2  0  0  1  2  3  4  5  6  7  8  9 10]
Flattened array: [10 10  6  4  2  0  0  1  2  3  4  5  6  7  8  9 10]
Original array:  [10  8  6  4  2  0  0  1  2  3  4  5  6  7  8  9 10]
Ravel array:  [10  8  6  4  2  0  0  1  2  3  4  5  6  7  8  9 10]


In [4]:
#TASK 04
import numpy as np

arr = np.linspace( 1.1, 6.6, num=6)
inttype = arr.astype('int32')
print("Integer array: ",inttype)
ftype = inttype.astype('float64')
print("FLoat array: ",ftype)
stype = ftype.astype(str)
print("String array: ",stype)

Integer array:  [1 2 3 4 5 6]
FLoat array:  [1. 2. 3. 4. 5. 6.]
String array:  ['1.0' '2.0' '3.0' '4.0' '5.0' '6.0']


In [5]:
#TASK 05
def formatting(arr):
    max_width = max(len(str(element)) for row in arr for element in row)
    formatted_array = [[f"{element:>{max_width}}" for element in row] for row in arr]
    formatted_string = '\n'.join([' '.join(row) for row in formatted_array])
    
    return formatted_string

arr = [
    [10, 22, 3],
    [45, 678, 9],
    [1, 23, 456]
]

display = formatting(arr)
print(display)


 10  22   3
 45 678   9
  1  23 456


In [7]:
#TASK 06
def dataFrames(data):
    width = [max(len(str(data[i][j])) for i in range(len(data))) for j in range(len(data[0]))]
    max_width = len(str(len(data)-1))
    
    format_df = []
    for i in range(len(data)):
        format_row = []
        for j in range(len(data[i])):
            format_element = f"{data[i][j]:>{width[j]}}"
            format_row.append(format_element)
        format_df.append(format_row)
    
    for index in range(len(format_df)):
        format_df[index] = [f"{index:>{max_width}}"] + format_df[index]
    
    format_df = [[' ' * max_width] + [f"{j:>{width[j]}}" for j in range(len(data[0]))]] + format_df
    format_string = '\n'.join([' '.join(row) for row in format_df])
    return format_string

data = [
    [11, 10, 6],
    [19, 55, 9],
    [3, 112, 555]
]

display = dataFrames(data)
print(display)


   0   1   2
0 11  10   6
1 19  55   9
2  3 112 555


In [ ]:
#TASK 07

board = [['*' for x in range(3)] for y in range(3)]

def gameBoard():
    for row in board:
        print(" | ".join(row))
        print("--" * 5)

def playerWin(player):
    # Winning conditions
    for i in range(3):
        if all(board[i][j] == player for j in range(3)) or all(board[j][i] == player for j in range(3)):
            return True
    if all(board[i][i] == player for i in range(3)) or all(board[i][2 - i] == player for i in range(3)):
        return True
    return False

def playerDraw():
    return all(board[i][j] != '*' for i in range(3) for j in range(3))

current_player = 'X'

while True:
    gameBoard()
    
    while True:
        try:
            row, col = map(int, input(f"Player {current_player}, enter your move (row and column): ").split())
            if board[row][col] == '*':
                break
            else:
                print("Invalid move. ")
        except (ValueError, IndexError):
            print("Invalid input. ")

    board[row][col] = current_player

    if playerWin(current_player):
        gameBoard()
        print(f"Player {current_player} wins!")
        break

    if playerDraw():
        gameBoard()
        print("It's a draw!")
        break

    current_player = 'X' if current_player == 'O' else 'O'


* | * | *
----------
* | * | *
----------
* | * | *
----------


In [ ]:
#TASK 08
import random

board = [[' ' for _ in range(3)] for _ in range(3)]

def gameBoard():
    for row in board:
        print(" | ".join(row))
        print("-" * 9)

def gameWin(player):
    # Check rows, columns, and diagonals for a win
    for i in range(3):
        if all(board[i][j] == player for j in range(3)) or all(board[j][i] == player for j in range(3)):
            return True
    if all(board[i][i] == player for i in range(3)) or all(board[i][2 - i] == player for i in range(3)):
        return True
    return False

def gameDraw():
    # Check if the game is a draw
    return all(board[i][j] != ' ' for i in range(3) for j in range(3))

def ComputerTurn():
    # Randomly select an empty square for the computer's move
    empty_squares = [(i, j) for i in range(3) for j in range(3) if board[i][j] == ' ']
    return random.choice(empty_squares)

def playerTurn():
    while True:
        try:
            row, col = map(int, input(f"Player {current_player}, enter your move (row and column): ").split())
            if board[row][col] == ' ':
                return row, col
            else:
                print("Invalid move. Square already occupied.")
        except (ValueError, IndexError):
            print("Invalid input. Please enter row and column as two integers.")

# Let the player choose to go first or second
first_player = input("Do you want to go first? (yes/no): ").lower()
human_player = 'X'
computer_player = 'O'

if first_player == 'no':
    human_player = 'O'
    computer_player = 'X'

current_player = human_player

while True:
    gameBoard()
    
    if current_player == human_player:
        row, col = playerTurn()
    else:
        row, col = computer_move()

    board[row][col] = current_player

    if check_win(current_player):
        gameBoard()
        if current_player == human_player:
            print(f"Player {current_player} wins!")
        else:
            print("Computer wins!")
        break

    if gameDraw():
        gameBoard()
        print("It's a draw!")
        break

    current_player = human_player if current_player == computer_player else computer_player


Do you want to go first? (yes/no): no
  |   |  
---------
  |   |  
---------
  |   |  
---------


In [ ]:
#TASK 09
def gameBoard(board):
    for i in range(4):
        print(f"Level {i + 1}")
        for j in range(4):
            print(" | ".join(board[i][j]))
            if j != 3:
                print("-" * 9)
        print()

def gameWin(board, player):
    for i in range(4):
        
        for j in range(4):
            if all(board[i][j][k] == player for k in range(4)) or all(board[i][k][j] == player for k in range(4)):
                return True

        if all(board[i][j][j] == player for j in range(4)) or all(board[i][j][3 - j] == player for j in range(4)):
            return True

        if all(board[k][j][j] == player for k in range(4)) or all(board[k][j][3 - j] == player for k in range(4)):
            return True

    for j in range(4):
        for k in range(4):
            if all(board[i][j][k] == player for i in range(4)):
                return True

  
    if all(board[i][j][j] == player for i in range(4)) or all(board[i][j][3 - j] == player for i in range(4)):
        return True

    return False

def gameDraw(board):
    return all(board[i][j][k] != ' ' for i in range(4) for j in range(4) for k in range(4))

board = [[[' ' for _ in range(4)] for _ in range(4)] for _ in range(4)]

current_player = 'X'

while True:
    gameBoard(board)

    while True:
        try:
            level, row, col = map(int, input(f"Player {current_player}, enter your move (level, row, and column): ").split())
            if board[level - 1][row - 1][col - 1] == ' ':
                break
            else:
                print("Invalid move. ")
        except (ValueError, IndexError):
            print("Invalid input. .")

    board[level - 1][row - 1][col - 1] = current_player

    if gameWin(board, current_player):
        gameBoard(board)
        print(f"Player {current_player} wins!")
        break

    if gameDraw(board):
        gameBoard(board)
        print("Game Drawn!")
        break

    current_player = 'O' if current_player == 'X' else 'X'


Level 1
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  

Level 2
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  

Level 3
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  

Level 4
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  

Player X, enter your move (level, row, and column): 1 2 3
Level 1
  |   |   |  
---------
  |   | X |  
---------
  |   |   |  
---------
  |   |   |  

Level 2
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  

Level 3
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  

Level 4
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  
---------
  |   |   |  



In [4]:
#TASK 10
import numpy as np

#Part (a)
arr1 = np.array([[0, 2], [4, 6]])
arr2 = np.array([[1, 3], [5, 7]])

arr3 = np.hstack((arr1, arr2))
print("Array 3:")
print(arr3, "\n")


#Part (b)
array4, array5 = np.vsplit(array3, 2)

print("Array 4:")
print(array4, "\n")

print("Array 5:")
print(array5, "\n")



#Part (c)
sorted_array4 = np.sort(array4)
sorted_array5 = np.sort(array5)

array6 = np.hstack((sorted_array4, sorted_array5))

print("Array 6:")
print(array6, "\n")



#Part (d)
array6_times_10 = array6 * 10

array7 = np.vstack((array6, array6_times_10))

print("Array 7:")
print(array7)

Array 3:
[[0 2 1 3]
 [4 6 5 7]] 

Array 4:
[[0 2 1 3]] 

Array 5:
[[4 6 5 7]] 

Array 6:
[[0 1 2 3 4 5 6 7]] 

Array 7:
[[ 0  1  2  3  4  5  6  7]
 [ 0 10 20 30 40 50 60 70]]


In [6]:
#TASK 11
import numpy as np

arr1 = np.random.randint(2, size=99)
arr2 = np.bincount(arr1)
print(f"Votes for Candidate 1: {arr1[0]}")
print(f"Votes for Candidate 2: {arr2[1]}")

Votes for Candidate 1: 0
Votes for Candidate 2: 30


In [13]:
#TASK 12
import numpy as np
from scipy import stats

def median(arr):
    return np.median(arr)

def mode(arr):
    return stats.mode(arr)


arr1 = np.array([9,8,7,6,5,4,3,2,1,0])
arr2 = np.array([[2, 3], [5, 6], [7, 8]])
arr3 = np.array([2,2,6,6,4,4,1,1,7,7])

median1 = median(arr1)
mode1 = mode(arr1)
median2 = median(arr2)
mode2 = mode(arr2)
median3 = median(arr3)
mode3 = mode(arr3)

print(f"Array 1 -> Median: {median1}, Mode: {mode1.mode[0]} (Count: {mode1.count[0]})")
print(f"Array 2 -> Median: {median2}, Mode: {mode2.mode[0]} (Count: {mode2.count[0]})")
print(f"Array 3 -> Median: {median3}, Mode: {mode3.mode[0]} (Count: {mode3.count[0]})")

Array 1 -> Median: 4.5, Mode: 0 (Count: 1)
Array 2 -> Median: 5.5, Mode: [2 3] (Count: [1 1])
Array 3 -> Median: 4.0, Mode: 1 (Count: 2)


C:\Users\Hp\AppData\Local\Temp\ipykernel_14996\1918532654.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return stats.mode(arr)


In [16]:
#TASK 13
import numpy as np
from scipy import stats

def median(arr, axis=None):
    return np.median(arr, axis=axis)

def mode(arr, axis=None):
    return stats.mode(arr, axis=axis)


array = np.array([[3, 2, 1], [7, 5, 9], [8, 0, 6]])

median_rows = median(array, axis=1)
mode_rows = mode(array, axis=1)

median_cols = median(array, axis=0)
mode_cols = mode(array, axis=0)

print(f"Rows median: {median_rows}")
print(f"Rows mode: {mode_rows.mode[0]} (Count: {mode_rows.count[0]})")

print(f"Columns median: {median_cols}")
print(f"COulmns mode: {mode_cols.mode[0]} (Count: {mode_cols.count[0]})")

Rows median: [2. 7. 6.]
Rows mode: [1] (Count: [1])
Columns median: [7. 2. 6.]
COulmns mode: [3 0 1] (Count: [1 1 1])


C:\Users\Hp\AppData\Local\Temp\ipykernel_14996\1164020985.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  return stats.mode(arr, axis=axis)


In [ ]:
#TASK 14
#Part ( a )
def knightsTourGame():
    board = [[0 for _ in range(8)] for _ in range(8)]

    current_number = 1
    current_row, current_column = 0, 0

    while current_number <= 64:
        board[current_row][current_column] = current_number

        gameBoard(board)

        current_number += 1

        next_row = int(input("Enter the next row (0-7): "))
        next_column = int(input("Enter the next column (0-7): "))

        if not (0 <= next_row < 8) or not (0 <= next_column < 8):
            print("Invalid input. ")
            continue

        if board[next_row][next_column] != 0:
            print("Invalid move.")
            continue

        current_row, current_column = next_row, next_column

def gameBoard(board):
    for row in board:
        print(" ".join(str(cell).rjust(2) for cell in row))

knightsTourGame()

 1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0


In [1]:
#Part ( b )
import numpy as np

board = np.zeros((8, 8), dtype=int)

horizontal = [2, 1, -1, -2, -2, -1, 1, 2]
vertical = [-1, -2, -2, -1, 1, 2, 2, 1]

current_row, current_column = 0, 0
move_count = 1

for movement in range(64):
    board[current_row][current_column] = move_count
    move_count += 1

    for index in range(8):
        new_row = current_row + vertical[index]
        new_column = current_column + horizontal[index]

        if (0 <= new_row < 8) and (0 <= new_column < 8) and (board[new_row][new_column] == 0):
            current_row, current_column = new_row, new_column
            break

print(board)

[[ 1 10 23 64  7  4 13 18]
 [24 41  8  3 12 17  6 15]
 [ 9  2 11 22  5 14 19 32]
 [ 0 25 40 35 20 31 16  0]
 [ 0 36 21  0 39  0 33 30]
 [26  0 38  0 34 29  0  0]
 [37  0  0 28  0  0  0  0]
 [ 0 27  0  0  0  0  0  0]]


In [3]:
#Part ( c )
import numpy as np

arr = np.array([
    [2, 3, 4, 4, 4, 4, 3, 2],
    [3, 4, 6, 6, 6, 6, 4, 3],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [3, 4, 6, 6, 6, 6, 4, 3],
    [2, 3, 4, 4, 4, 4, 3, 2]
])

board = np.zeros((8, 8), dtype=int)

horizontal = [2, 1, -1, -2, -2, -1, 1, 2]
vertical = [-1, -2, -2, -1, 1, 2, 2, 1]

current_row, current_column = 0, 0
move_count = 1

for movement in range(64):
    board[current_row][current_column] = move_count
    move_count += 1
    arr -= 1
    min_access = float('inf')
    for i in range(8):
        new_row = current_row + vertical[i]
        new_column = current_column + horizontal[i]

        if (0 <= new_row < 8) and (0 <= new_column < 8) and (board[new_row][new_column] == 0) and (arr[new_row][new_column] < min_access):
            min_access = arr[new_row][new_column]
            next_row, next_column = new_row, new_column

    current_row, current_column = next_row, next_column

print(board)

[[ 1 32  3 18 29 34 13 16]
 [ 4 19 30 33 14 17 28 35]
 [31  2 55 58 53 44 15 12]
 [20  5 52 43 56 27 36 45]
 [51 42 57 54 59  0 11 26]
 [ 6 21 64  0  0  0 46 37]
 [41 50 23  8 39 48 25 10]
 [22  7 40 49 24  9 38 47]]
